apiVersion: v1
kind: Pod
metadata:
  name: gate
  namespace: gatenet
  labels:
    app: gate
  annotations:
    security.alpha.kubernetes.io/unsafe-sysctls: net.ipv4.conf.all.rp_filter=0,net.ipv4.conf.default.rp_filter=0
spec:
  containers:
  - name: gate
    image: "orkun1675/cni-gatenet:0.1"
    tty: true
    volumeMounts:
    - mountPath: /mnt/cni-conf
      name: cni-conf
    - mountPath: /mnt/kube-conf/kubeconfig
      name: kube-conf
    - mountPath: /etc/kubernetes/certs
      name: kube-cert
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
  nodeSelector:
    app: gate
  volumes:
  - name: cni-conf
    hostPath:
      path: /etc/cni/net.d
  - name: kube-conf
    hostPath:
      path: /var/lib/kubelet/kubeconfig
  - name: kube-cert
    hostPath:
      path: /etc/kubernetes/certs
